name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup-graalvm-ce
        uses: rinx/setup-graalvm-ce@master
        with:
          graalvm-version: "20.1.0"
          java-version: "java11"
          native-image: "true"
      - name: native-image version
        run: |
          native-image --version
