name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup-graalvm-ce
        uses: rinx/setup-graalvm-ce@master
        with:
          graalvm-version: "19.3.0"
          java-version: "java11"
      - name: setup-native-image
        run: |
          gu install native-image
