name: Test
on: push

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: setup-graalvm-ce
        uses: rinx/setup-graalvm-ce@master
        with:
          graalvm-version: "19.3.0"
          java-version: "java11"
      - name: setup-native-image
        run: |
          gu install native-image
  test-macos:
    runs-on: macos-latest
    steps:
      - name: setup-graalvm-ce
        uses: rinx/setup-graalvm-ce@master
        with:
          graalvm-version: "19.3.0"
          java-version: "java11"
          platform: "darwin"
      - name: setup-native-image
        run: |
          gu install native-image
  test-windows:
    runs-on: windows-latest
    steps:
      - name: setup-graalvm-ce
        uses: rinx/setup-graalvm-ce@master
        with:
          graalvm-version: "19.3.0"
          java-version: "java11"
          platform: "windows"
      - name: setup-native-image
        run: |
          gu install native-image
